R1QA=https://dcodecnr1dev1.unilever.com/ngui/
ProdR1=https://dcode.unilever.com/ngui/
R2QA=https://dcodecnr1dev1.unilever.com/ngui/
AstronDEV=https://danonengdev.centegyapps.com/ngui
AstronSIT=https://danonengsit.centegyapps.com/ngui

