package org.example.ui.utilities;

import org.apache.logging.log4j.Logger;
import org.apache.poi.ss.usermodel.*;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.nio.file.Paths;
import java.time.Duration;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static org.example.ui.utilities.LoaderWait.waitForLoaderToDisappear;

/**
 * Handles the complete PJP upload flow, which is sequential by nature:
 *
 *   DSR Bulk Upload
 *        -> read generated DSR Code
 *        -> insert DSR Code into Header Excel
 *        -> upload Header Excel
 *        -> read generated Header/PJP Code
 *        -> insert Header/PJP Code into Detail Excel
 *        -> upload Detail Excel
 *        -> run UI Search validation
 *
 * Kept as its own class (instead of the generic "dependsOn" mechanism)
 * because every step here depends on data generated by the previous one.
 *
 * All column names / test IDs used to look up generated values are read from
 * Scenario Data — nothing is hardcoded.
 */
public class PJPExcelUpload {

    private static final Logger logger = LoggerUtil.getLogger(PJPExcelUpload.class);

    public static ValidationResult run(WebDriver driver,
                                       Map<String, Object> dsrScreen,
                                       Map<String, Object> headerScreen,
                                       Map<String, Object> detailScreen,
                                       Map<String, String> scenarioData,
                                       String downloadDir) throws Exception {

        logger.info("=====================================================");
        logger.info("🚀 Starting PJP Upload Flow");
        logger.info("=====================================================");

        // ---------- STEP 1: DSR Bulk Upload ----------
        logger.info("Step 1: Uploading DSR Excel...");
        uploadScreenRespectingMode(driver, dsrScreen);
        logger.info("Step 1 complete: DSR Excel uploaded.");

        // ---------- STEP 2: Read Generated DSR Code ----------
        String dsrTestId = scenarioData.get("DSRTestId");
        String dsrGeneratedColumn = scenarioData.get("DSRGeneratedColumn");

        String dsrCode = GeneratedDataStore.get(dsrTestId, dsrGeneratedColumn);
        logger.info("Step 2: Generated DSR Code = [{}]", dsrCode);

        if (dsrCode == null || dsrCode.isBlank()) {
            throw new RuntimeException(
                    "DSR Code not found in GeneratedDataStore for testId: " + dsrTestId
                            + ", column: " + dsrGeneratedColumn
                            + ". Check that the DSR screen's mode/rules actually generate this column.");
        }

        // ---------- STEP 3: Update Header Excel with DSR Code ----------
        String headerTemplatePath = (String) headerScreen.get("templatePath");
        String headerDsrColumn = scenarioData.get("PJPHeaderDSRColumn");

        logger.info("Step 3: Updating Header Excel column [{}] with value [{}]",
                headerDsrColumn, dsrCode);
        updateColumnValue(headerTemplatePath, headerDsrColumn, dsrCode);
        logger.info("Step 3 complete: Header Excel updated.");

        // ---------- STEP 4: Upload Header Excel ----------
        logger.info("Step 4: Uploading Header Excel...");

        uploadScreenRespectingMode(driver, headerScreen);
        logger.info("Step 4 complete: Header Excel uploaded.");

        // ---------- STEP 5: Read Generated Header/PJP Code ----------
        String headerTestId = scenarioData.get("PJPHeaderTestId");
        String headerGeneratedColumn = scenarioData.get("PJPHeaderGeneratedColumn");

        String pjpCode = GeneratedDataStore.get(headerTestId, headerGeneratedColumn);
        logger.info("Step 5: Generated Header/PJP Code = [{}]", pjpCode);

        if (pjpCode == null || pjpCode.isBlank()) {
            throw new RuntimeException(
                    "Header/PJP Code not found in GeneratedDataStore for testId: " + headerTestId
                            + ", column: " + headerGeneratedColumn);
        }

        // ---------- STEP 6: Update Detail Excel with Header/PJP Code ----------
        String detailTemplatePath = (String) detailScreen.get("templatePath");
        String PJPNoColumnInConfig = scenarioData.get("PJPNoColumnInConfig");

        logger.info("Step 6: Updating Detail Excel column [{}] with value [{}]",
                PJPNoColumnInConfig, pjpCode);
        updateColumnValue(detailTemplatePath, PJPNoColumnInConfig, pjpCode);
        logger.info("Step 6 complete: Detail Excel updated.");

        // ---------- STEP 7: Upload Detail Excel ----------
        logger.info("Step 7: Uploading Detail Excel...");
        uploadScreenRespectingMode(driver, detailScreen);
        logger.info("Step 7 complete: Detail Excel uploaded.");

        // ---------- STEP 8: UI Search Validation ----------
        String PJPConfigTestId = scenarioData.get("PJPConfigTestId");

        logger.info("Step 8a: Registering PJP Code under DetailTestId [{}] for UI Search validation...",
                PJPConfigTestId);
        GeneratedDataStore.store(PJPConfigTestId, PJPNoColumnInConfig, pjpCode);

        @SuppressWarnings("unchecked")
        Map<String, Map<String, Object>> detailValidations =
                (Map<String, Map<String, Object>>) detailScreen.get("validations");

        Map<String, Object> validationsSheet =
                (detailValidations != null) ? detailValidations.get(PJPConfigTestId) : null;

        if (validationsSheet == null) {
            throw new RuntimeException(
                    "No validation configuration found for testId: " + PJPConfigTestId);
        }

//        String validateMode = String.valueOf(
//                detailScreen.getOrDefault("validateMode", "UI_SEARCH"));

        logger.info("Step 8b: Running UI Search Validation (mode={})...", "UI_SEARCH");

        ValidationResult result = PostUploadValidator.run(
                driver,
                validationsSheet,
                PJPConfigTestId,
                detailTemplatePath,
                downloadDir,
                "UI_SEARCH",
                scenarioData
        );

        logger.info("Step 8 complete: Validation finished.");
        logger.info("=====================================================");
        logger.info("✅ PJP Upload Flow Completed");
        logger.info("=====================================================");


        return result;
    }

    // -------------------------------------------------------------------
    // Navigates to the screen and uploads the right file for its mode,
    // mirroring the same branches Main.java's switch already handles —
    // reused here instead of duplicated, so DOWNLOAD_UPDATE_UPLOAD screens
    // (like DSR, which generates UUID columns via ExcelGen) actually
    // populate GeneratedDataStore before we try to read from it.
    // -------------------------------------------------------------------
    @SuppressWarnings("unchecked")
    private static void uploadScreenRespectingMode(WebDriver driver, Map<String, Object> screen) throws Exception {
        String screenName = (String) screen.get("screenName");
        String screenId = (String) screen.get("screenId");
        String templatePath = (String) screen.get("templatePath");
        String testId = (String) screen.get("testID");
        Map<String, Map<String, Object>> rules =
                (Map<String, Map<String, Object>>) screen.get("rules");

        navigateToScreen(driver, screenName, screenId);

        // Generate via ExcelGen whenever rules exist for this screen — this is
        // what actually populates GeneratedDataStore with fresh, unique values
        // (e.g. DSR Code, PJP Number). We key off "rules present", not "mode",
        // because a screen's mode (e.g. "PJP" on the Header row) may not
        // literally be DOWNLOAD_UPDATE_UPLOAD even though it still needs
        // generated data.
        if (rules != null && !rules.isEmpty()) {
            logger.info("  -> Generating Excel for testId [{}] (rules present: true)", testId);
            String generatedFile = ExcelGen.generateExcel(templatePath, rules, testId);
            FileManager.uploadFile(driver, screenName, generatedFile);
            FileManager.downloadExcel(driver, screenName, null);
        } else {
            logger.info("  -> No rules configured for testId [{}], uploading static template", testId);
            FileManager.uploadFile(driver, screenName, templatePath);
            FileManager.downloadExcel(driver, screenName, null);
        }
    }

    private static void navigateToScreen(WebDriver driver, String screenName, String screenId) throws Exception {
        waitForLoaderToDisappear(driver);

        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));

        try {
            wait.until(ExpectedConditions.elementToBeClickable(By.id("menurollin")));
            Event.robustClick(driver, By.id("menurollin"));
        } catch (Exception e) {
            wait.until(ExpectedConditions.visibilityOfElementLocated(
                    By.cssSelector("input[placeholder='Search Here']")));
        }

        WebElement searchBox = wait.until(
                ExpectedConditions.elementToBeClickable(
                        By.cssSelector("input[placeholder='Search Here']")));

        searchBox.clear();
        searchBox.sendKeys(screenName);
        Thread.sleep(400);

        wait.until(ExpectedConditions.elementToBeClickable(By.id(screenId)));
        Event.robustClick(driver, By.id(screenId));

        waitForLoaderToDisappear(driver);
    }

    private static void updateColumnValue(String filePath, String columnName, String newValue) throws Exception {
        FileInputStream fis = new FileInputStream(filePath);
        Workbook workbook = WorkbookFactory.create(fis);
        fis.close();

        Sheet sheet = workbook.getSheetAt(0);
        Row headerRow = sheet.getRow(0);

        if (headerRow == null) {
            workbook.close();
            throw new RuntimeException("Header row missing in Excel: " + filePath);
        }

        int columnIndex = -1;
        for (Cell cell : headerRow) {
            if (columnName.equalsIgnoreCase(cell.getStringCellValue().trim())) {
                columnIndex = cell.getColumnIndex();
                break;
            }
        }

        if (columnIndex == -1) {
            workbook.close();
            throw new RuntimeException("Column '" + columnName + "' not found in Excel: " + filePath);
        }

        for (int i = 1; i <= sheet.getLastRowNum(); i++) {
            Row row = sheet.getRow(i);
            if (row == null) continue;

            Cell cell = row.getCell(columnIndex);
            if (cell == null) {
                cell = row.createCell(columnIndex);
            }
            cell.setCellValue(newValue);
        }

        FileOutputStream fos = new FileOutputStream(filePath);
        workbook.write(fos);
        fos.close();
        workbook.close();
    }
    /**
     * Finds a screen config (row from the Excel-config sheet) by its testID,
     * and resolves its templatePath to an absolute path against resourcesFolder.
     * Used by the PJP flow to fetch the DSR / Header / Detail screen configs
     * referenced from the PJP row's scenarioData.
     */
    public static Map<String, Object> findScreenByTestId(
            List<Map<String, Object>> screens,
            String testId,
            String resourcesFolder) {

        if (testId == null || testId.isBlank()) {
            throw new RuntimeException(
                    "PJP scenarioData is missing a required testId (DSRTestId / PJPHeaderTestId / PJPConfigTestId).");
        }

        for (Map<String, Object> screen : screens) {
            if (testId.equals(screen.get("testID"))) {
                // Return a shallow copy so we don't mutate the shared config list
                // when resolving templatePath to an absolute path.
                Map<String, Object> resolved = new LinkedHashMap<>(screen);

                String templatePath = (String) resolved.get("templatePath");
                if (templatePath != null) {
                    String rootPath = System.getProperty("user.dir") + File.separator + resourcesFolder;
                    resolved.put("templatePath", Paths.get(rootPath, templatePath).toString());
                }

                return resolved;
            }
        }

        throw new RuntimeException("No screen found in config with testID: " + testId);
    }
}